import type { Metadata } from "next";
import { lexend } from "@/lib/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Stealth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend} bg-background text-foreground`}>
        {children}
      </body>
    </html>
  );
}
