import type { Metadata } from "next";
import { lexend } from "@/lib/font";
import "./globals.css";
import { ThemeProvider } from "next-themes"
import ReactQueryProvider from "@/lib/react-query-provider";

export const metadata: Metadata = {
  title: "Stealth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${lexend} bg-background text-foreground`}>
        <ReactQueryProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
